class NavBar:

    def __init__(self, browser):
        self.browser = browser
        # Navbar
        self.navbar = "//header"

        self.home_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[1]"

        self.base_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[2]"

        self.finance_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[3]"
        self.payments_button_nav = "//li[@class='dropdown open']//li[1]"
        self.accruals_button_nav = "//li[@class='dropdown open']//li[2]"
        self.commission_button_nav = "//li[@class='dropdown open']//li[3]"
        self.rebound_contracts_button_nav = "//li[@class='dropdown open']//li[4]"

        self.tariffs_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[4]"
        self.false_packages_button_nav = "//div[@class='col-sm-3 col-md-2'][1]/ul[@class='list-unstyled'][2]/li[1]"
        self.rules_of_false_packages_button_nav = \
            "//div[@class='col-sm-3 col-md-2'][1]/ul[@class='list-unstyled'][2]/li[2]"
        self.tariff_lines_button_nav = "//div[@class='col-sm-3 col-md-2'][2]/ul[@class='list-unstyled'][2]/li[1]"
        self.tariff_plans_button_nav = "//div[@class='col-sm-3 col-md-2'][2]/ul[@class='list-unstyled'][2]/li[2]"
        self.services_button_nav = "//div[@class='col-sm-3 col-md-2'][2]/ul[@class='list-unstyled'][2]/li[3]"
        self.parameters_button_nav = "//div[@class='col-sm-3 col-md-2'][2]/ul[@class='list-unstyled'][2]/li[4]"
        self.description_templates_button_nav = \
            "//div[@class='col-sm-3 col-md-2'][2]/ul[@class='list-unstyled'][2]/li[5]"
        self.restrictions_shares_button_nav = "//div[@class='col-sm-3 col-md-2'][3]/ul[@class='list-unstyled'][2]/li[1]"
        self.min_tariff_restrictions_button_nav = \
            "//div[@class='col-sm-3 col-md-2'][3]/ul[@class='list-unstyled'][2]/li[2]"
        self.default_tariff_button_nav = "//div[@class='col-sm-3 col-md-2'][3]/ul[@class='list-unstyled'][2]/li[3]"
        self.export_tariff_button_nav = "//div[@class='col-sm-3 col-md-2'][3]/ul[@class='list-unstyled'][2]/li[4]"

        self.dealers_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[5]"
        self.dealers_dealers_button_nav = "//li[@class='dropdown open']//li[1]"
        self.create_dealers_button_nav = "//li[@class='dropdown open']//li[2]"
        self.classification_button_nav = "//li[@class='dropdown open']//li[3]"

        self.tasks_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[6]"

        self.orders_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[7]"
        self.all_orders_button_nav = "//li[@class='dropdown open']//li[1]"
        self.current_orders_button_nav = "//li[@class='dropdown open']//li[2]"
        self.mail_button_nav = "//li[@class='dropdown open']//li[3]"
        self.pickup_button_nav = "//li[@class='dropdown open']//li[4]"

        self.storage_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[8]"
        self.cloud_button_nav = "//li[@class='dropdown open']//li[1]"
        self.reissue_button_nav = "//li[@class='dropdown open']//li[2]"
        self.mask_button_nav = "//li[@class='dropdown open']//li[3]"
        self.mask_category_button_nav = "//li[@class='dropdown open']//li[4]"
        self.save_button_nav = "//li[@class='dropdown open']//li[5]"
        self.task_queue_button_nav = "//li[@class='dropdown open']//li[6]"
        self.labels_button_nav = "//li[@class='dropdown open']//li[7]"
        self.booking_button_nav = "//li[@class='dropdown open']//li[8]"
        self.frod_button_nav = "//li[@class='dropdown open']//li[9]"

        self.tools_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[9]"
        self.group_operations_button_nav = "//li[@class='dropdown open']//li[1]"
        self.passports_button_nav = "//li[@class='dropdown open']//li[2]"
        self.number_signs_button_nav = "//li[@class='dropdown open']//li[3]"
        self.spartak_lottery_button_nav = "//li[@class='dropdown open']//li[4]"

        self.reports_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[10]"
        self.all_reports_button_nav = "//li[10]//div[@class='col-sm-3 col-md-2'][1]//li[1]"
        self.ban_settings_button_nav = "//li[10]//div[@class='col-sm-3 col-md-2'][1]//li[2]"
        self.month_statistic_button_nav = "//li[10]//div[@class='col-sm-3 col-md-2'][1]//li[3]"
        self.report1_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[1]/div"
        self.report2_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[2]/div"
        self.report3_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[3]/div"
        self.report4_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[4]/div"
        self.report5_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[5]/div"
        self.report6_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[6]/div"
        self.report7_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[7]/div"
        self.report8_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[8]/div"
        self.report9_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[9]/div"
        self.report10_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[10]/div"
        self.report11_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[11]/div"
        self.report12_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[12]/div"
        self.report13_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[13]/div"
        self.report14_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[14]/div"
        self.report15_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[15]/div"
        self.report16_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[16]/div"
        self.report17_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[17]/div"
        self.report18_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[18]/div"
        self.report19_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[19]/div"
        self.report20_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[20]/div"
        self.report21_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[21]/div"
        self.report22_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[22]/div"
        self.report23_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[23]/div"
        self.report24_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[24]/div"
        self.report25_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[25]/div"
        self.report26_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[26]/div"
        self.report27_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[27]/div"
        self.report28_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[28]/div"
        self.report29_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[29]/div"
        self.report30_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[30]/div"
        self.report31_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[31]/div"
        self.report32_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[32]/div"
        self.report33_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[33]/div"
        self.report34_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[34]/div"
        self.report35_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[35]/div"
        self.report36_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[36]/div"
        self.report37_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[37]/div"
        self.report38_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[38]/div"
        self.report39_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[39]/div"
        self.report40_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[40]/div"
        self.report41_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[41]/div"
        self.report42_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[42]/div"
        self.report43_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[43]/div"
        self.report44_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[44]/div"
        self.report45_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[45]/div"
        self.report46_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[46]/div"
        self.report47_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[47]/div"
        self.report48_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[48]/div"
        self.report49_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[49]/div"
        self.report50_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[50]/div"
        self.report51_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[51]/div"
        self.report52_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[52]/div"
        self.report53_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[53]/div"
        self.report54_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[54]/div"
        self.report55_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[55]/div"
        self.report56_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[56]/div"
        self.report57_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[57]/div"
        self.report58_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[58]/div"
        self.report59_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[59]/div"
        self.report60_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[60]/div"
        self.report61_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[61]/div"
        self.report62_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[62]/div"
        self.report63_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[63]/div"
        self.report64_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[64]/div"
        self.report65_button_nav = "//li[10]//div[@class='col-sm-9 col-md-10']/div[65]/div"

        self.admin_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[11]"
        self.timekeeper_button_nav = "//li[11]//div/div[@class='row']/div[1]//li[1]"
        self.timetable_button_nav = "//li[11]//div/div[@class='row']/div[1]//li[2]"
        self.personal_adjustments_button_nav = "//li[11]//div/div[@class='row']/div[1]//li[3]"
        self.visit_log_button_nav = "//li[11]//div/div[@class='row']/div[1]//li[4]"
        self.timekeeper_report_button_nav = "//li[11]//div/div[@class='row']/div[1]//li[5]"
        self.ban_accounts_button_nav = "//li[11]//div/div[@class='row']/div[2]//li[1]"
        self.access_rights_button_nav = "//li[11]//div/div[@class='row']/div[2]//li[2]"
        self.vacation_button_nav = "//li[11]//div/div[@class='row']/div[2]//li[3]"
        self.ats_button_nav = "//li[11]//div/div[@class='row']/div[2]//li[4]"
        self.roles_button_nav = "//li[11]//div/div[@class='row']/div[3]//li[1]"
        self.permission_button_nav = "//li[11]//div/div[@class='row']/div[3]//li[2]"
        self.routes_button_nav = "//li[11]//div/div[@class='row']/div[3]//li[3]"
        self.exceptions_button_nav = "//li[11]//div/div[@class='row']/div[3]//li[4]"
        self.tk_event_log_button_nav = "//li[11]//div/div[@class='row']/div[4]//li[1]"
        self.area_codes_button_nav = "//li[11]//div/div[@class='row']/div[4]//li[2]"
        self.accounts_button_nav = "//li[11]//div/div[@class='row']/div[5]//li[1]"

        self.twins_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[11]"
        self.control_panel_button_nav = "//li[@class='dropdown open']//li[1]"
        self.storage_twins_button_nav = "//li[@class='dropdown open']//li[2]"
        self.dealers_exceptions_button_nav = "//li[@class='dropdown open']//li[3]"

        self.card_index_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[13]"

        self.callcenter_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[14]"
        self.incoming_button_nav = "//li[@class='dropdown open']//li[1]"
        self.categories_button_nav = "//li[@class='dropdown open']//li[2]"
        self.appeal_button_nav = "//li[@class='dropdown open']//li[3]"
        self.solutions_button_nav = "//li[@class='dropdown open']//li[4]"
        self.qc_incoming_button_nav = "//li[@class='dropdown open']//li[5]"
        self.qc_topics_button_nav = "//li[@class='dropdown open']//li[6]"
        self.qc_reasons_button_nav = "//li[@class='dropdown open']//li[7]"

        self.cashless_button_nav = "//ul[@class='nav navbar-top-links pull-left']/li[15]"

        self.phone_search_button_nav = "//ul[@class='nav pull-right']"
        self.phone_search_field_nav = "//input[@class='select2-search__field']"
        self.phone_number_button_nav = "//li[@class='select2-results__option']"

        self.profile_button_nav = "//ul[@class='nav navbar-top-links pull-right']/li"
        self.my_profile_button_nav = "//ul[@class='nav navbar-top-links pull-right']/li//li[1]"
        self.change_password_button_nav = "//ul[@class='nav navbar-top-links pull-right']/li//li[2]"
        self.exit_button_nav = "//ul[@class='nav navbar-top-links pull-right']/li//li[3]"
