class CatalogLocators:

    catalog_page_url = 'https://bill.bezlimit.ru/phone/catalog/index'
    catalog_page_bill1_url = 'http://bill1.bezlimit.ru/phone/catalog/index'

    # catalog tabs
    catalog_tab_button = "//ul[@id='w8']/li[1]"
    birthday_tab_button = "//ul[@id='w8']/li[2]"
    block_tab_button = "//ul[@id='w8']/li[3]"
    none_ban_tab_button = "//ul[@id='w8']/li[4]"
    none_ban_mnp_tab_button = "//ul[@id='w8']/li[5]"

    # catalog buttons
    reset_filters_button = "//a[@class='btn btn-sm btn-purple btn-icon fal fa-filter']"
    copy_button = "//button[@id='w2']"
    export_button = "//a[@class='btn btn-success btn-sm btn-labeled fal fa-table']"
    export_pd_button = "//a[@class='btn btn-info btn-sm btn-labeled fal fa-passport']"
    results_export_button = "//a[@class='btn btn-success btn-sm btn-labeled fal fa-download']"
    group_search_button = "//button[@class='btn btn-dark-gray btn-sm btn-labeled fal fa-search']"
    group_operation_button = "//button[@id='w3']"
    sms_distribution_button = "//button[@id='w4']"
    columns_button = "//button[@class='btn btn-sm btn-mint btn-labeled fa fa-cog']"

    number_of_records_total = "//div[@id='grid']/div/b[2]"

    # Sort buttons
    total_checkbox = "//thead/tr/th[1]/input"
    phone_number_sort_button = "//thead/tr/th[2]/a"
    status_sort_button = "//thead/tr/th[3]/a"
    date_activation_sort_button = "//thead/tr/th[4]/a"
    date_blocking_sort_button = "//thead/tr/th[5]/a"
    expiration_date_sort_button = "//thead/tr/th[6]/a"
    balance_sort_button = "//thead/tr/th[7]/a"
    current_accrual_sort_button = "//thead/tr/th[9]/a"
    balance_plus_score_sort_button = "//thead/tr/th[10]/a"
    contact_person_sort_button = "//thead/tr/th[11]/a"
    blocking_prohibition_sort_button = "//thead/tr/th[14]/a"
    comment_blocking_prohibition_sort_button = "//thead/tr/th[15]/a"
    unblocking_prohibition_sort_button = "//thead/tr/th[16]/a"
    comment_unblocking_prohibition_sort_button = "//thead/tr/th[17]/a"
    id_dealer_sort_button = "//thead/tr/th[19]/a"
    category_sort_button = "//thead/tr/th[22]/a"
    main_digit_number_sort_button = "//thead/tr/th[23]/a"
    code_sort_button = "//thead/tr/th[26]/a"
    mask_sort_button = "//thead/tr/th[29]/a"
    reservation_sort_button = "//thead/tr/th[32]/a"
    arpu_sort_button = "//thead/tr/th[33]/a"
    package_sort_button = "//thead/tr/th[34]/a"
    secret_word_sort_button = "//thead/tr/th[38]/a"
    camel_sort_button = "//thead/tr/th[40]/a"
    financial_status_sort_button = "//thead/tr/th[43]/a"
    payment_sort_button = "//thead/tr/th[45]/a"
    unprofitable_subscriber_sort_button = "//thead/tr/th[46]/a"
    prohibition_false_tariff_sort_button = "//thead/tr/th[47]/a"
    frod_dangerous_blocking_prohibition_sort_button = "//thead/tr/th[49]/a"
    sign_number_store_sort_button = "//thead/tr/th[54]/a"
    sign_number_sort_button = "//thead/tr/th[59]/a"
    main_group_number_sort_button = "//thead/tr/th[61]/a"
    free_output_sort_button = "//thead/tr/th[62]/a"

    # Filters
    phone_number_filter_field = "//tr[@id='grid-filters']/td[2]/input"
    status_filter_select = "//tr[@id='grid-filters']/td[3]/select"
    date_activation_first_filter_field = "//tr[@id='grid-filters']/td[4]/input[1]"
    date_activation_second_filter_field = "//tr[@id='grid-filters']/td[4]/input[2]"
    date_blocking_first_filter_field = "//tr[@id='grid-filters']/td[5]/input[1]"
    date_blocking_second_filter_field = "//tr[@id='grid-filters']/td[5]/input[2]"
    expiration_date_first_filter_field = "//tr[@id='grid-filters']/td[6]/input[1]"
    expiration_date_second_filter_field = "//tr[@id='grid-filters']/td[6]/input[2]"
    balance_filter_field = "//tr[@id='grid-filters']/td[7]/input"
    balance_without_fluidity_filter_field = "//tr[@id='grid-filters']/td[8]/input"
    current_accrual_filter_field = "//tr[@id='grid-filters']/td[9]/input"
    balance_plus_score_filter_field = "//tr[@id='grid-filters']/td[10]/input"
    contact_person_filter_button = "//tr[@id='grid-filters']/td[11]/span"
    ban_filter_button = "//tr[@id='grid-filters']/td[12]/span"
    partner_sign_filter_select = "//tr[@id='grid-filters']/td[13]/select"
    blocking_prohibition_filter_select = "//tr[@id='grid-filters']/td[14]/select"
    comment_blocking_prohibition_filter_field = "//tr[@id='grid-filters']/td[15]/input"
    unblocking_prohibition_filter_select = "//tr[@id='grid-filters']/td[16]/select"
    comment_unblocking_prohibition_filter_field = "//tr[@id='grid-filters']/td[17]/input"
    international_roaming_filter_select = "//tr[@id='grid-filters']/td[18]/select"
    id_dealer_filter_field = "//tr[@id='grid-filters']/td[19]/input"
    dealer_branch_filter_button = "//tr[@id='grid-filters']/td[20]/div/span[1]"
    dealer_branch_button = "//tr[@id='grid-filters']/td[20]/div/span[2]/button"
    template_filter_field = "//tr[@id='grid-filters']/td[21]/input"
    category_filter_select = "//tr[@id='grid-filters']/td[22]/select"
    main_digit_number_filter_field = "//tr[@id='grid-filters']/td[23]/input"
    minimum_tariff_limitation_filter_field = "//tr[@id='grid-filters']/td[24]/input"
    paid_blocking_filter_select = "//tr[@id='grid-filters']/td[25]/select"
    code_filter_select = "//tr[@id='grid-filters']/td[26]/select"
    auto_payment_filter_select = "//tr[@id='grid-filters']/td[27]/select"
    tariff_filter_button = "//tr[@id='grid-filters']/td[28]/span"
    type_filter_select = "//tr[@id='grid-filters']/td[30]/select"
    technical_name_tp_filter_field = "//tr[@id='grid-filters']/td[31]/input"
    reservation_filter_select = "//tr[@id='grid-filters']/td[32]/select"
    arpu_filter_field = "//tr[@id='grid-filters']/td[33]/input"
    package_filter_field = "//tr[@id='grid-filters']/td[34]/input"
    flag_pa_filter_select = "//tr[@id='grid-filters']/td[35]/select"
    flag_fpa_filter_select = "//tr[@id='grid-filters']/td[36]/select"
    flag_sim_filter_select = "//tr[@id='grid-filters']/td[37]/select"
    secret_word_filter_field = "//tr[@id='grid-filters']/td[38]/input"
    full_name_filter_field = "//tr[@id='grid-filters']/td[39]/input"
    camel_filter_select = "//tr[@id='grid-filters']/td[40]/select"
    bezlimit_subscription_pay_filter_field = "//tr[@id='grid-filters']/td[41]/span"
    beeline_subscription_pay_filter_field = "//tr[@id='grid-filters']/td[42]/span"
    financial_status_filter_select = "//tr[@id='grid-filters']/td[43]/select"
    have_services_filter_select = "//tr[@id='grid-filters']/td[44]/select"
    payment_filter_select = "//tr[@id='grid-filters']/td[45]/select"
    unprofitable_subscriber_filter_select = "//tr[@id='grid-filters']/td[46]/select"
    prohibition_false_tariff_filter_select = "//tr[@id='grid-filters']/td[47]/select"
    passport_data_filter_select = "//tr[@id='grid-filters']/td[48]/select"
    frod_dangerous_blocking_prohibition_filter_select = "//tr[@id='grid-filters']/td[49]/select"
    limit_block_filter_field = "//tr[@id='grid-filters']/td[50]/input"
    activation_limit_filter_field = "//tr[@id='grid-filters']/td[51]/input"
    telegram_filter_select = "//tr[@id='grid-filters']/td[52]/select"
    mask_price_filter_field = "/tr[@id='grid-filters']/td[53]/input"
    sign_number_store_filter_select = "//tr[@id='grid-filters']/td[54]/select"
    sign_number_mnp_filter_select = "//tr[@id='grid-filters']/td[55]/select"
    time_life_number_filter_field = "//tr[@id='grid-filters']/td[56]/input"
    number_active_days_filter_field = "//tr[@id='grid-filters']/td[57]/input"
    percent_life_number_filter_field = "//tr[@id='grid-filters']/td[58]/input"
    sign_number_filter_select = "//tr[@id='grid-filters']/td[59]/select"
    number_implementation_resource_filter_select = "//tr[@id='grid-filters']/td[60]/select"
    main_group_number_filter_field = "//tr[@id='grid-filters']/td[61]/input"
    free_output_first_filter_field = "//tr[@id='grid-filters']/td[62]/input[1]"
    free_output_second_filter_field = "//tr[@id='grid-filters']/td[62]/input[2]"
    region_filter_select = "//tr[@id='grid-filters']/td[63]/select"

    span_filter_field = "//body/span/span/span//input[@type='search']"
    span_ban_filter_field = "//input[@type='search']"
    span_list_item = "//span[@class='select2-results']/ul/li"

    # Messages
    filter_err_message = "//tr[@id='grid-filters']/td"
